config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: 'homes#top'
  get "home/about", to: "homes#about"

  get 'search', to:'searches#search'
  get 'search_tag', to: 'searches#search_tag'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationship, only: [:show, :create, :destroy]
    member do
      get :followers
      get :followeds
      get :datebooks
    end
  end

  resources :chats, only: [:show, :create, :destroy]
  resources :groups, only: [:new, :index, :show, :edit, :update, :create, :destroy] do
    member do
      get :join
      get :new_mail
      get :send_mail
    end
  end

  resources :notifications, only: [:update]

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  validates :name, presence: true, uniqueness: true
  has_one_attached :group_image

  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end

  def joined_by?(user)
    user_groups.exists?(user_id: user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit, :destroy, :notice]
  def index
    @groups = Group.all
    @book = Book.new
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group), notice: "You have updated group successfully."
    else
      redirect_to groups_path
    end
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      current_user.user_groups.create(group_id: @group.id)
      redirect_to group_path(@group), notice: "You have created group successfully."
    else
      render :new
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to groups_path
  end

  def join
    @group = Group.find(params[:id])
    UserGroup.create(user_id: current_user.id, group_id: @group.id)
    redirect_to group_path(@group)
  end

  def leave
    @group = Group.find(params[:id])
    user_group = UserGroup.find_by(user_id: current_user.id, group_id: @group.id)
    user_group.destroy
    redirect_to group_path(@group)
  end

  def new_mail
    @group = Group.find(params[:id])
  end
  
  def send_mail
    @group = Group.find(params[:id])
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mailer(@mail_title, @mail_content, @group).deliver_now
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    unless Group.find(params[:id]).owner_id == current_user.id
      redirect_to groups_path
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model:group, local:true do |f| %>
  <%= render 'layouts/errors', obj: @group %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control name" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :group_image, class: "form-control-file group_image", accept: 'image/*' %>
  </div>
  <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "form-control introduction" %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/groups/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th>intro</th>
      <th>member</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_group_image, size: '50x50' %></td>
        <td><%= link_to group.name, group_path(group) %></td>
        <td><%= group.introduction %></td>
        <td>メンバー数：<%= group.users.count %></td>
        <% if group.owner_id == current_user.id %>
          <td>
            <%= link_to "Edit", edit_group_path(group), class: 'btn btn-sm btn-success' %>
          </td>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/_join.html.erb
<% if group.joined_by?(current_user) %>
  <%= link_to "Leave this group", leave_group_path(group), class: 'btn btn-sm btn-danger' %>
<% else %>
  <%= link_to "Join this group", join_group_path(group), class: 'btn btn-sm btn-primary' %>
<% end %>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Group</h1>
  		<%= render 'groups/form', group: @group %>

      <div class="d-flex justify-content-end">
        <%= link_to 'Delete', group_path(@group), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: '本当に消しますか？' } %>
      </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>

    <div class="row mb-2">
      <div class="col">
        <h2 class="mb-0">Groups</h2>
      </div>
      <div class="col px-3 d-flex justify-content-end align-items-end">
        <%= link_to 'Group Index', groups_path %>
        <span class="mx-2">|</span>
        <%= link_to 'Group Create', new_group_path %>
      </div>
    </div>

    <%= render 'index',groups: @groups %>

    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Group Create</h2>
    <%= render 'groups/form', group: @group %>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Event Mail</h2>
      <%= form_with url: send_mail_group_path(@group),method: :get, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :mail_title, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%=f.label :content %>
        <%= f.text_area :mail_content, class: 'form-control' %>
      </div>
      <div>
        <%= f.submit'送信', class: "btn btn-sm btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container d-flex flex-column align-items-center text-left">
  <div>
    <h3 class="mb-3">送信が完了しました</h3>
    <p class="mb-1">内容は以下の通りです。</p>
    <div>
      [タイトル]<p class="font-weight-bold"> <%= @mail_title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"> <%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>

      <div class="row mb-2">
        <div class="col">
          <h2 class="mb-0">Group Detail</h2>
        </div>
        <div class="col px-3 d-flex justify-content-end align-items-end">
          <%= link_to 'Group Index', groups_path %>
          <span class="mx-2">|</span>
          <%= link_to 'Group Create', new_group_path %>
        </div>
      </div>

      <table class='table'>
        <tbody>
        <tr>
          <td><%= image_tag @group.get_group_image, size: '50x50' %></td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>メンバー数：<%= @group.users.count %></td>
          <% if @group.owner_id == current_user.id %>
            <td>
              <%= link_to "Edit", edit_group_path(@group), class: 'btn btn-sm btn-success' %>
            </td>
          <% else %>
            <td>
              <%= render 'groups/join', group: @group %>
            </td>
          <% end %>
        </tr>
        </tbody>
      </table>

      <div class="mb-3">
      <span><strong>メンバー（名前順）</strong></span>
      <span>
        <% if @group.owner_id == current_user.id %>
          <%= link_to "Notice an Event", new_mail_group_path(@group), class: "btn btn-sm btn-info" %>
        <% end %>
      </span>
      </div>
      <% @group.users.order(:name).each do |user| %>
        <% if @group.owner_id == user.id %>
          <p><%= user.name %>（Owner）</p>
        <% else %>
          <p><%= user.name %></p>
        <% end %>
      <% end %>


    </div>
  </div>
</div>