config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: 'homes#top'
  get "home/about", to: "homes#about"

  get 'search', to:'searches#search'
  get 'search_tag', to: 'searches#search_tag'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationship, only: [:show, :create, :destroy]
    member do
      get :followers
      get :followeds
      get :datebooks
    end
  end

  resources :chats, only: [:show, :create, :destroy]
  resources :groups, only: [:new, :index, :show, :edit, :update, :create, :destroy] do
    member do
      get :join
      get :new_mail
      get :send_mail
    end
  end

  resources :notifications, only: [:update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :show_counts, dependent: :destroy

  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  # time間以内のfavorites順並び替えスコープ
  # scope :populer_last, -> (time) {
  #   sort { |a, b| b.favorites.where('created_at >= ?', time).size <=> a.favorites.where('created_at >= ?', time).size }
  # }

  scope :new_order, -> { order(created_at: :desc) }
  scope :old_order, -> { order(created_at: :asc) }
  scope :star_order, -> { order(star: :desc) }
  scope :favorite_order, -> { sort { |a, b| b.favorites.where('created_at >= ?', Time.zone.now.last_week).size <=> a.favorites.where('created_at >= ?', Time.zone.now.last_week).size } }
  scope :asc_title_order, -> { order(title: :asc) }
  scope :desc_title_order, -> { order(title: :desc) }

  scope :today_books, -> { where(created_at: Time.zone.now.all_day) }
  scope :yesterday_books, -> { where(created_at: Time.zone.now.yesterday.all_day) }
  scope :thisweek_books, -> { where(created_at: Time.zone.now.prev_week(:saturday)..Time.zone.now) }
  scope :lastweek_books, -> { where(created_at: Time.zone.now.last_week.prev_week(:saturday)..Time.zone.now.prev_week(:friday).end_of_day) }

  scope :lastday_books, -> (day) { where(created_at: Time.zone.now.ago(day.days).all_day) }
  scope :date_books, -> (date) { where(created_at: date.all_day) }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
  validates :tag_id, uniqueness: { scope: :book_id }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: {maximum: 140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  has_one :notification, as: :notifiable, dependent: :destroy

  validates :user_id, uniqueness: {scope: :book_id}

  after_create do
    create_notification(user_id: book.user_id)
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  validates :name, presence: true, uniqueness: true
  has_one_attached :group_image

  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end

  def joined_by?(user)
    user_groups.exists?(user_id: user.id)
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"  

  validates :follower_id, uniqueness: {scope: :followed_id}
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_room, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/show_count.rb
class ShowCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :book_tags, dependent: :destroy
  has_many :books, through: :book_tags
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followed_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  has_one_attached :profile_image

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms

  has_many :show_counts, dependent: :destroy

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups

  has_many :notifications, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def followed_by?(user)
    followers.exists?(followed_id: user.id)
  end

  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :user_id, uniqueness: { scope: :group_id }
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuser signed in successfully"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]
  before_action :ensure_guest_user, only: [:edit]

  def show
    # 個人ページの本を並び変えるならココ
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def datebooks
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @date = params[:date].to_date
    @datebooks = @books.date_books(@date)
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def followers
    user = User.find(params[:id])
    @users = user.followed_user
  end

  def followeds
    user = User.find(params[:id])
    @users = user.follower_user
  end


  def edit
    @user = current_user
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user), notice: "this user cannot access"
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user), notice: "Guest user cannot access"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_datebooks.html.erb
<div class="mt-3">
  <%= form_with url: datebooks_user_path(user.id), local: false, method: :get do |f| %>
    <%= f.date_field :date, value: params[:date] %>
    <%= f.submit "Search"%>
  <% end %>

  <% unless datebooks.nil? %>
  <span><%= params[:date].to_date.strftime("%Y年%m月%d日")%>の投稿数：<%= @datebooks.count %></span>
  <% end %>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followeds.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <% if user != current_user %>
          <td>
            <%= render 'relationships/relationship', user: user %>
          </td>
        <% else %>
          <td></td>
        <% end %>

        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followeds.count, followeds_user_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user.id) %></th>
  </tr>
</table>

<% if user != current_user %>
  <%= render 'relationships/relationship', user: user %>
<% else %>
  <% unless user.guest_user? %>
    <div class='row'>
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/datebooks.js.erb
$(".user-datebooks").html("<%= escape_javascript(render partial: 'users/datebooks', locals: {user: @user, books: @books, datebooks: @datebooks}) %>");

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followeds.html.erb
<div class='container px-5 px-sm-0'>
  <h2>Follow Users</h2>

  <%= render 'users/index', users: @users %>

</div>

app/views/users/followers.html.erb
<div class='container px-5 px-sm-0'>
  <h2>Follower Users</h2>

  <%= render 'users/index', users: @users %>

</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>

      <div class="row mb-2">
        <div class="col">
          <h2 class="mb-0">Users</h2>
        </div>
        <div class="col px-3 d-flex justify-content-end align-items-end">
          <%= link_to 'Group Index', groups_path %>
          <span class="mx-2">|</span>
          <%= link_to 'Group Create', new_group_path %>
        </div>
      </div>

      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <div>
        <h2 class="mt-3">投稿数の前日比・前週比</h2>
        <table class='table table-hover table-bordered'>
          <thead class="thead-light">
            <tr>
              <th>今日の投稿数</th>
              <th>昨日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tr>
            <td><%= @books.today_books.count %></td>
            <td><%= @books.yesterday_books.count %></td>
            <td>
              <% if @books.yesterday_books.count == 0 %>
                <span>前日の投稿はありません</span>
              <% else %>
                <span><%= (@books.today_books.count.to_f / @books.yesterday_books.count.to_f * 100).round(1) %>%</span>
              <% end %>
            </td>
          </tr>
        </table>

        <table class='table table-hover table-bordered'>
          <thead class="thead-light">
            <tr>
              <th>今週の投稿数</th>
              <th>前週の投稿数</th>
              <th>前週比</th>
            </tr>
          </thead>
          <tr>
            <td><%= @books.thisweek_books.count %></td>
            <td><%= @books.lastweek_books.count %></td>
            <td>
              <% if @books.lastweek_books.count == 0 %>
                <span>先週の投稿はありません</span>
              <% else %>
                <span><%= (@books.thisweek_books.count.to_f / @books.lastweek_books.count.to_f * 100).round(1) %>%</span>
              <% end %>
            </td>
          </tr>
        </table>
        
        <h2 class="mt-3">前７日間の投稿数</h2>
        <table class='table table-hover table-bordered'>
          <thead class="thead-light">
            <tr>
              <th>６日前</th>
              <th>５日前</th>
              <th>４日前</th>
              <th>３日前</th>
              <th>２日前</th>
              <th>１日前</th>
              <th>今日</th>
            </tr>
          </thead>
          <tr>
            <td><%= @books.lastday_books(6).count %></td>
            <td><%= @books.lastday_books(5).count %></td>
            <td><%= @books.lastday_books(4).count %></td>
            <td><%= @books.lastday_books(3).count %></td>
            <td><%= @books.lastday_books(2).count %></td>
            <td><%= @books.lastday_books(1).count %></td>
            <td><%= @books.lastday_books(0).count %></td>
          </tr>
        </table>

        <canvas id="myLineChart" class="py-3"></canvas>

        <script>
          $(document).on('turbolinks:load', function() {
            var ctx = document.getElementById("myLineChart");
            var myLineChart = new Chart(ctx, {
              type: 'line',
              data: {
                labels: ['６日前', '５日前', '４日前', '３日前', '２日前', '１日前', '今日'],
                datasets: [
                  {
                    label: '投稿数',
                    data: [ <%= @books.lastday_books(6).count %>, 
                            <%= @books.lastday_books(5).count %>,
                            <%= @books.lastday_books(4).count %>,
                            <%= @books.lastday_books(3).count %>,
                            <%= @books.lastday_books(2).count %>,
                            <%= @books.lastday_books(1).count %>,
                            <%= @books.lastday_books(0).count %>
                          ],
                    borderColor: "rgba(0,0,255,1)",
                    backgroundColor: "rgba(0,0,0,0)"
                  },
                ],
              },
              options: {
                title: {
                  display: true,
                  text: '７日間の投稿数の比較'
                },
                scales: {
                  yAxes: [{
                    ticks: {
                      suggestedMax: 10,
                      suggestedMin: 0,
                      stepSize: 1,
                      callback: function(value, index, values){
                        return  value +  '冊'
                      }
                    }
                  }]
                },
              }
            });
          });
        </script>
        

        <div class="user-datebooks">
          <%= render 'users/datebooks', user: @user, books: @books, datebooks: @datebooks %>
        </div>

      </div>

    </div>
  </div>
</div>