config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: 'homes#top'
  get "home/about", to: "homes#about"

  get 'search', to:'searches#search'
  get 'search_tag', to: 'searches#search_tag'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationship, only: [:show, :create, :destroy]
    member do
      get :followers
      get :followeds
      get :datebooks
    end
  end

  resources :chats, only: [:show, :create, :destroy]
  resources :groups, only: [:new, :index, :show, :edit, :update, :create, :destroy] do
    member do
      get :join
      get :new_mail
      get :send_mail
    end
  end

  resources :notifications, only: [:update]

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :show_counts, dependent: :destroy

  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  # time間以内のfavorites順並び替えスコープ
  # scope :populer_last, -> (time) {
  #   sort { |a, b| b.favorites.where('created_at >= ?', time).size <=> a.favorites.where('created_at >= ?', time).size }
  # }

  scope :new_order, -> { order(created_at: :desc) }
  scope :old_order, -> { order(created_at: :asc) }
  scope :star_order, -> { order(star: :desc) }
  scope :favorite_order, -> { sort { |a, b| b.favorites.where('created_at >= ?', Time.zone.now.last_week).size <=> a.favorites.where('created_at >= ?', Time.zone.now.last_week).size } }
  scope :asc_title_order, -> { order(title: :asc) }
  scope :desc_title_order, -> { order(title: :desc) }

  scope :today_books, -> { where(created_at: Time.zone.now.all_day) }
  scope :yesterday_books, -> { where(created_at: Time.zone.now.yesterday.all_day) }
  scope :thisweek_books, -> { where(created_at: Time.zone.now.prev_week(:saturday)..Time.zone.now) }
  scope :lastweek_books, -> { where(created_at: Time.zone.now.last_week.prev_week(:saturday)..Time.zone.now.prev_week(:friday).end_of_day) }

  scope :lastday_books, -> (day) { where(created_at: Time.zone.now.ago(day.days).all_day) }
  scope :date_books, -> (date) { where(created_at: date.all_day) }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new

    # 24時間内に同名アクセスしたかどうか
    time = Time.zone.now
    unless ShowCount.where('created_at >= ?', time.yesterday).find_by(user_id: current_user.id, book_id: @book.id)
      current_user.show_counts.create(book_id: @book.id)
    end
  end

  def index
    # time = Time.zone.now
    # @books = Book.all.populer_last(time.last_week)
    @book = Book.new

    @books = Book.all
    unless params[:how_order].nil?
      if @books.respond_to? params[:how_order]
        @books = @books.send(params[:how_order])
      end
    end

    # if params[:how_order] == "new_order"
    #   @books = Book.new_order
    # elsif params[:how_order] == "old_order"
    #   @books = Book.old_order
    # elsif params[:how_order] == "star_order"
    #   @books = Book.star_order
    # elsif params[:how_order] == "favorite_order"
    #   time = Time.zone.now
    #   @books = Book.all.populer_last(time.last_week)
    # else
    #   @books = Book.all
    # end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user

    if @book.save
      # タグの作成
      @tags = params[:book][:tag].split(',')
      @tags.each do |tag|
        tag = Tag.find_or_create_by(name: tag.gsub(/　/," ").strip)
        tag.book_tags.create(book_id: @book.id)
      end

      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star)
  end

  def ensure_correct_user
    @user = Book.find(params[:id]).user
    unless @user == current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= render 'layouts/errors', obj: book %>

<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_field :tag, id: :tag_names, class: 'form-control book_title', placeholder: "tags split','" %>
  </div>

  <% if book.id.nil? %>
    <div class="form-group">
      <%= f.label :star %>
      <%= f.hidden_field :star, id: :review_star %>
      <div id="post_raty"></div>
    </div>


    <script>

      $(document).on('turbolinks:load', function() {
        $('#post_raty').empty();
        let elem = document.querySelector('#post_raty');
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem,opt);
      });
    </script>
  <% else %>
    <div class="form-group">
      <%= render 'books/static_star', book: book %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th>Star</th>
      <th>Good</th>
      <th>Comment</th>
      <th>View</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td>
          <% book.book_tags.each do |book_tag| %>
            <div>
              <%= link_to book_tag.tag.name, search_tag_path(tag_word: book_tag.tag.name) %>
            </div>
          <% end %>
        </td>
        <td><%= render 'books/static_star', book: book %></td>
        <td class="favorite-<%= book.id %>" ><%= render 'favorites/favorite', book: book %></td>
        <td><%= book.book_comments.count %></td>
        <td><%= book.show_counts.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_static_star.html.erb
<div id="star-<%= book.id %>"></div>

<script>
  $(document).on('turbolinks:load', function() {
    $('#star-<%= book.id %>').empty();
    let elem = document.querySelector('#star-<%= book.id %>');
    let opt = {
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      score: "<%= book.star %>",
      readOnly: true,
    };
    raty(elem,opt);
  });
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <div class="row">
        <div class="col">
          <h2 class="mb-0">Books</h2>
        </div>

        <div class="col px-3 d-flex justify-content-end">
          <%= form_with url: books_path, method: :get, class: "py-2 text-right" do |f| %>
            <%= f.select :how_order, options_for_select([
              ["New","new_order"],
              ["Old","old_order"],
              ["Star","star_order"],
              ["Good","favorite_order"],
              ["Title_asc","asc_title_order"],
              ["Title_desc","desc_title_order"]
              ],selected: params[:how_order]) %>
            <%= f.submit "Order" %>
          <% end %>
        </div>

      </div>
  
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= render 'books/static_star', book: @book %></td>
          <td class="favorite-<%= @book.id %>" ><%= render 'favorites/favorite', book: @book %></td>
          <td>コメント数：<%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>

      <span class="book-comments">
        <%= render 'book_comments/book_comments', book: @book, book_comment: @book_comment %>
      </span>

    </div>
  </div>
</div>